// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	/// <summary>PID: 10 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int rngminheader_10 = 10;
	/// <summary>PID: 10 | Type: read</summary>
	public const int rngminheader = 10;
	/// <summary>PID: 11 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int rngmaxheader_11 = 11;
	/// <summary>PID: 11 | Type: read</summary>
	public const int rngmaxheader = 11;
	/// <summary>PID: 12 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int rngcountheader_12 = 12;
	/// <summary>PID: 12 | Type: read</summary>
	public const int rngcountheader = 12;
	/// <summary>PID: 13 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int rngresponsestatuscode_13 = 13;
	/// <summary>PID: 13 | Type: read</summary>
	public const int rngresponsestatuscode = 13;
	/// <summary>PID: 14 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int rngresponsecontent_14 = 14;
	/// <summary>PID: 14 | Type: read</summary>
	public const int rngresponsecontent = 14;
	/// <summary>PID: 15 | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public const int randomValue_15 = 15;
	/// <summary>PID: 15 | Type: read</summary>
	public const int randomValue = 15;
	public class Write
	{
		/// <summary>PID: 110 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rngminheader_110 = 110;
		/// <summary>PID: 110 | Type: write</summary>
		public const int rngminheader = 110;
		/// <summary>PID: 111 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rngmaxheader_111 = 111;
		/// <summary>PID: 111 | Type: write</summary>
		public const int rngmaxheader = 111;
		/// <summary>PID: 112 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int rngcountheader_112 = 112;
		/// <summary>PID: 112 | Type: write</summary>
		public const int rngcountheader = 112;
	}
}
public class WriteParameters
{
	/// <summary>PID: 110  | Type: write</summary>
	public System.Object Rngminheader {get { return Protocol.GetParameter(110); }set { Protocol.SetParameter(110, value); }}
	/// <summary>PID: 111  | Type: write</summary>
	public System.Object Rngmaxheader {get { return Protocol.GetParameter(111); }set { Protocol.SetParameter(111, value); }}
	/// <summary>PID: 112  | Type: write</summary>
	public System.Object Rngcountheader {get { return Protocol.GetParameter(112); }set { Protocol.SetParameter(112, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Afterstartup_dummy { get; set; }
	object Ip_ip { get; set; }
	object Rngminheader_10 { get; set; }
	object Rngminheader { get; set; }
	object Rngmaxheader_11 { get; set; }
	object Rngmaxheader { get; set; }
	object Rngcountheader_12 { get; set; }
	object Rngcountheader { get; set; }
	object Rngresponsestatuscode_13 { get; set; }
	object Rngresponsestatuscode { get; set; }
	object Rngresponsecontent_14 { get; set; }
	object Rngresponsecontent { get; set; }
	object RandomValue_15 { get; set; }
	object RandomValue { get; set; }
	object Rngminheader_110 { get; set; }
	object Rngmaxheader_111 { get; set; }
	object Rngcountheader_112 { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 2  | Type: dummy</summary>
	public System.Object Afterstartup_dummy {get { return GetParameter(2); }set { SetParameter(2, value); }}
	/// <summary>PID: 5  | Type: ip</summary>
	public System.Object Ip_ip {get { return GetParameter(5); }set { SetParameter(5, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngminheader_10 {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 10  | Type: read</summary>
	public System.Object Rngminheader {get { return GetParameter(10); }set { SetParameter(10, value); }}
	/// <summary>PID: 11  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngmaxheader_11 {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 11  | Type: read</summary>
	public System.Object Rngmaxheader {get { return GetParameter(11); }set { SetParameter(11, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngcountheader_12 {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 12  | Type: read</summary>
	public System.Object Rngcountheader {get { return GetParameter(12); }set { SetParameter(12, value); }}
	/// <summary>PID: 13  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngresponsestatuscode_13 {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 13  | Type: read</summary>
	public System.Object Rngresponsestatuscode {get { return GetParameter(13); }set { SetParameter(13, value); }}
	/// <summary>PID: 14  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngresponsecontent_14 {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 14  | Type: read</summary>
	public System.Object Rngresponsecontent {get { return GetParameter(14); }set { SetParameter(14, value); }}
	/// <summary>PID: 15  | Type: read</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object RandomValue_15 {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 15  | Type: read</summary>
	public System.Object RandomValue {get { return GetParameter(15); }set { SetParameter(15, value); }}
	/// <summary>PID: 110  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngminheader_110 {get { return GetParameter(110); }set { SetParameter(110, value); }}
	/// <summary>PID: 111  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngmaxheader_111 {get { return GetParameter(111); }set { SetParameter(111, value); }}
	/// <summary>PID: 112  | Type: write</summary>
	[EditorBrowsable(EditorBrowsableState.Never)]
	public System.Object Rngcountheader_112 {get { return GetParameter(112); }set { SetParameter(112, value); }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
